# Generated by Django 4.0.5 on 2022-06-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Date_published',
            field=models.DateTimeField(),
        ),
    ]
